package com.swordfish.lemuroid.app.mobile.shared.compose.ui

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFFF3131) // Nothing Red
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD6)
val md_theme_light_onPrimaryContainer = Color(0xFF410002)
val md_theme_light_secondary = Color(0xFF444444)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8E8E8)
val md_theme_light_onSecondaryContainer = Color(0xFF1A1A1A)
val md_theme_light_tertiary = Color(0xFF666666)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD4D4D4)
val md_theme_light_onTertiaryContainer = Color(0xFF111111)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF5F5F5)
val md_theme_light_onBackground = Color(0xFF0D0D0D)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF0D0D0D)
val md_theme_light_surfaceVariant = Color(0xFFE0E0E0)
val md_theme_light_onSurfaceVariant = Color(0xFF444444)
val md_theme_light_outline = Color(0xFF888888)
val md_theme_light_inverseOnSurface = Color(0xFFF0F0F0)
val md_theme_light_inverseSurface = Color(0xFF1A1A1A)
val md_theme_light_inversePrimary = Color(0xFFCCCCCC)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFFF3131)
val md_theme_light_outlineVariant = Color(0xFFCCCCCC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFF3131) // Nothing Red
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFF93000A)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD6)
val md_theme_dark_secondary = Color(0xFFAAAAAA)
val md_theme_dark_onSecondary = Color(0xFF1A1A1A)
val md_theme_dark_secondaryContainer = Color(0xFF333333)
val md_theme_dark_onSecondaryContainer = Color(0xFFDDDDDD)
val md_theme_dark_tertiary = Color(0xFF888888)
val md_theme_dark_onTertiary = Color(0xFF0D0D0D)
val md_theme_dark_tertiaryContainer = Color(0xFF2A2A2A)
val md_theme_dark_onTertiaryContainer = Color(0xFFDDDDDD)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0D0D0D)
val md_theme_dark_onBackground = Color(0xFFF0F0F0)
val md_theme_dark_surface = Color(0xFF161616)
val md_theme_dark_onSurface = Color(0xFFF0F0F0)
val md_theme_dark_surfaceVariant = Color(0xFF1F1F1F)
val md_theme_dark_onSurfaceVariant = Color(0xFFAAAAAA)
val md_theme_dark_outline = Color(0xFF555555)
val md_theme_dark_inverseOnSurface = Color(0xFF0D0D0D)
val md_theme_dark_inverseSurface = Color(0xFFF0F0F0)
val md_theme_dark_inversePrimary = Color(0xFFFF3131)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFF3131)
val md_theme_dark_outlineVariant = Color(0xFF333333)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFFFF3131)
